- name: Delpoy a web application
  hosts: db_and_web_server1,db_and_web_server2

  tasks:
    - name: Install all required dependencies
      apt: name="{{ item }}" state=present
      with_items:
        - python3
        - python3-pip
        - nginx
        - git
        - python3-venv
        - python3-dev
        - build-essential
        - libssl-dev